### PR TITLE
Add last login timestamp

### LINKED ISSUE #14: Last login timestamp
This is a sub issue of #9 

### Tasks
- Add a field in user schema which holds the last login timestamp of an user.

### PR DESCRIPTION
**Pull request by n1l4y**
This PR closes #14 

### Changes
- add `lastLogin` field to User schema
- update `lastLogin` timestamp on successful login.

### CODE REVIEW

**Review by HarshDobariya79 — CHANGES_REQUESTED** [review]
Thank you for adding the timestamps @n1l4y.

Currently the document looks like this.
image

We also need one timestamp for the `lastLogin`, which I think we manually need to maintain. So can you please add that field as not required initially and when login is successful, update the lastLogin timestamp?

Please try to add corresponding types as well if required and don't forget to run `npm run lint:fix` and `npm run format` before commit. Thanks.

**Comment by n1l4y** [comment]
Please check if it's working now?

**Comment by HarshDobariya79** [comment]
> Please check if it's working now?

The model looks good now. I think the login API changes aren't present in your commit. You need to update the last login timestamp manually after generating the JWT in the login endpoint. Please add that logic in the `user.service.ts` file.

**Comment by n1l4y** [comment]
image
added lastLogin timestamp, which is saved in db

**Review by HarshDobariya79 — APPROVED** [review]
Thank you for implementing the required changes. Great work.

**Pull request merged**
