### PR TITLE
added a pull_request_template.md

### LINKED ISSUE #32: template: github pr template
### Tasks
- [ ] Create a pr template for GitHub which have sections like,
  - Issue reference section like (This PR closes # )
  - Additional changes (this section contains other minor changes which might not be mentioned in the issue description like small bug fixes)

### PR DESCRIPTION
**Pull request by jaydoshi2**
This PR closes #32

### CODE REVIEW

**Review by HarshDobariya79 — CHANGES_REQUESTED** [review]
Please check the issue description and implement only what is mentioned. Don't add any content which manually needs to be removed every time.

**Comment by jaydoshi2** [comment]
okay I'll do it

**Review by HarshDobariya79 — CHANGES_REQUESTED** [review]
Please only implement what is asked in the issue, and omit any help text. Keep the template as clean and minimalistic as possible.

**Comment by jaydoshi2** [comment]
I have done the changes please review it and suggest me if any changes are needed.

**Review by HarshDobariya79 — CHANGES_REQUESTED** [review]
Can you please remove the placeholders further more? Please remove all placeholders enclosed in [] and keep only one - in the additional changes.

**Comment by HarshDobariya79** [comment]
Any update @jaydoshi2?

**Pull request closed without merging**
